include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "lib/l10n/messages_*.dart"
    - "**.g.dart"
    - "**.freezed.dart"
  errors:
    import_of_legacy_library_into_null_safe: ignore

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    one_member_abstracts: false
