name: flutter_graphql_practice
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.0.4"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0-nullsafety.5
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.14.0
  json_serializable: ^4.1.0
  freezed_annotation: ^0.14.0

dev_dependencies:
  build_runner: ^1.12.0
  freezed: ^0.14.0
  effective_dart: ^1.3.0
